#!/usr/bin/env perl
# -*- perl -*-

=head1 NAME

irc - Plugin to graph the rping of a server's uplink(s) from GenEthic. 

=head1 CONFIGURATION

You must set env.path to the genethic.log file outputted by GenEthic.

  [irc]
    env.logdir  /home/bot/var/genethic.log

=head1 AUTHOR

MrIron <iron@masterbofh.org>

=head1 LICENSE

GPLv3

=head1 MAGIC MARKERS

  #%# family=manual
  #%# capabilities=autoconf

=cut

use POSIX;

my $LOGDIR = $ENV{'logdir'} || '/usr/home/bot/var';

my $modification = -M "$LOGDIR/genethic.log";
my $lastupdated = ceil(time() - $modification);

my @uplinks;

if ($ARGV[0] and $ARGV[0] eq "autoconf") {
  if ( ! -r "$LOGDIR/genethic.log" ) {
    print "log file not found or wrong permissions\n";
    exit 0;
  }
  print "yes\n";
  exit 0;
}

open(LOG,"$LOGDIR/genethic.log");
while(<LOG>)
{
	if ( /RPING_(.*?)\.(.*?):(\d+)$/ )
	{	
		$data{$1} = $3;
		push(@uplinks, $1);
	}
}

close(LOG);

if($ARGV[0] and $ARGV[0] eq "config") {
	print "host_name $ENV{FQDN}\n";
	print "graph_title irc rping\n";
	print "graph_category irc\n";
	print "graph_vlabel Rping in milliseconds\n";
	print "graph_order @uplinks\n";
	print "graph_args -l 0\n";

	foreach (@uplinks)
	{	
		print "$_.label $_\n";
		print "$_.draw LINE2\n";
	}

    exit 0;
}

foreach (@uplinks)
{
	print "$_.value $lastupdated:$data{$_}\n";
}
